// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Runtime.Serialization;

namespace GitHub.Services.Profile
{
    [DataContract]
    public class Avatar : ITimeStamped, ICloneable
    {
        [DataMember]
        public byte[] Value { get; set; }

        [DataMember(IsRequired = false, EmitDefaultValue = false)]
        public DateTimeOffset TimeStamp { get; set; }

        [DataMember(IsRequired = false, EmitDefaultValue = false)]
        public AvatarSize Size { get; internal set; }

        [DataMember(IsRequired = false, EmitDefaultValue = false)]
        public bool? IsAutoGenerated { get; internal set; }

        public object Clone()
        {
            var clone = new Avatar()
            {
                Size = this.Size,
                TimeStamp = this.TimeStamp,
                IsAutoGenerated = this.IsAutoGenerated
            };
            if (Value != null)
            {
                clone.Value = new byte[Value.Length];
                Buffer.BlockCopy(Value, 0, clone.Value, 0, Value.Length);
            }
            return clone;
        }
    }

    /// <summary>
    /// Small = 34 x 34 pixels; Medium = 44 x 44 pixels; Large = 220 x 220 pixels
    /// </summary>
    [DataContract]
    public enum AvatarSize
    {
        Small,
        Medium,
        Large,
    }
}
