# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish Docker Image from Source Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag to build from (e.g., v2.316.1)'
        required: true
  pull_request:
    branches:
      - google-main

jobs:
  publish-image:
    runs-on: linux-x86-n2-16-buildkit
    container: google/cloud-sdk:524.0.0
    permissions:
      contents: read
      id-token: write
      attestations: write
    env:
      REGISTRY: us-docker.pkg.dev
      IMAGE_NAME: ml-actions-platform-production/ml-actions-production-registry/actions-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.inputs.tag || '' }}
          # Fetch full history/metadata so that git rev-parse HEAD works for the build telemetry
          fetch-depth: 0

      - name: Trust Git workspace directory
        run: git config --global --add safe.directory ${{ github.workspace }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3.11.1
        with:
          driver: remote
          endpoint: tcp://localhost:1234

      - name: Log into registry ${{ env.REGISTRY }}
        run: gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          # Use the root of the repo as the build context so it can copy the source files
          context: .
          file: ./images/Dockerfile.source
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ github.event.inputs.tag && format('{0}/{1}:{2}', env.REGISTRY, env.IMAGE_NAME, github.event.inputs.tag) || '' }}
            ${{ github.event_name == 'pull_request' && format('{0}/{1}:pr-{2}', env.REGISTRY, env.IMAGE_NAME, github.event.pull_request.number) || format('{0}/{1}:latest', env.REGISTRY, env.IMAGE_NAME) }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: |
            org.opencontainers.image.source=${{github.server_url}}/${{github.repository}}
            org.opencontainers.image.licenses=Apache-2.0
          annotations: |
            org.opencontainers.image.description=GitHub Actions Runner built from source ${{ github.event.inputs.tag && format('at tag {0}', github.event.inputs.tag) || format('for PR #{0}', github.event.pull_request.number) }}

      - name: Generate attestation
        if: github.event_name != 'pull_request'
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build-and-push.outputs.digest }}
          push-to-registry: true
